#!/usr/bin/env python3
"""Turn Google's service-account JSON into .streamlit/secrets.toml.

Converting that file by hand is the most error-prone step in the whole setup —
the private key is a single long line full of \\n escapes, and one stray
newline or a swapped quote style makes it unreadable in a way the error message
does not explain. This does the conversion mechanically instead.

Usage, from the repository root:

    python tools/make_secrets.py ~/Downloads/your-key.json <spreadsheet-key>

The spreadsheet key is the long string in your sheet's URL, between /d/ and /edit.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REQUIRED = ["type", "project_id", "private_key_id", "private_key",
            "client_email", "client_id", "token_uri"]

OPTIONAL = ["auth_uri", "auth_provider_x509_cert_url", "client_x509_cert_url",
            "universe_domain"]


def to_toml(credentials: dict, spreadsheet_key: str) -> str:
    """Render the TOML.

    Values go through json.dumps, which produces exactly the escaping a TOML
    basic string needs — so the private key's newlines come out as literal \\n
    rather than breaking the file across lines.
    """
    lines = ["# Generated by tools/make_secrets.py — do not commit this file.",
             "",
             "[gcp_service_account]"]

    for field in REQUIRED + OPTIONAL:
        if field in credentials:
            lines.append(f"{field} = {json.dumps(credentials[field])}")

    lines += ["", "[sheets]", f"spreadsheet_key = {json.dumps(spreadsheet_key)}", ""]
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip())
        return 1

    source = Path(sys.argv[1]).expanduser()
    spreadsheet_key = sys.argv[2].strip()

    if not source.exists():
        print(f"Cannot find {source}. Check the path — drag the file into Terminal "
              "to paste its exact location.")
        return 1

    try:
        credentials = json.loads(source.read_text())
    except ValueError as error:
        print(f"{source.name} is not valid JSON ({error}). Make sure you picked the key "
              "file Google downloaded, not something else.")
        return 1

    missing = [field for field in REQUIRED if field not in credentials]
    if missing:
        print("That JSON is missing: " + ", ".join(missing))
        print("It should be the service account key — it starts with "
              '{"type": "service_account", ...}')
        return 1

    if "/" in spreadsheet_key or spreadsheet_key.startswith("http"):
        print("Pass just the key, not the whole URL — the part between /d/ and /edit.")
        return 1

    target = Path(".streamlit/secrets.toml")
    if target.exists():
        answer = input(f"{target} already exists. Overwrite? [y/N] ").strip().lower()
        if answer != "y":
            print("Left it alone.")
            return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(to_toml(credentials, spreadsheet_key))

    print(f"Wrote {target}")
    print(f"Service account: {credentials['client_email']}")
    print()
    print("Make sure that address has Editor access to your spreadsheet, then restart "
          "the app. Delete the downloaded JSON once you have confirmed it works.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
